# Generated by Django 4.2.25 on 2025-10-02 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='unique_sensor_timestamp'),
        ),
    ]
